### ISSUE TITLE
MTP-II versus MTP-2

### ISSUE THREAD

**Issue by uvwxy** [bitbank2/Print2BLE#1]
My device (GOOJPRT) announces itself as "MTP-II" instead of "MTP-2" and is thus not picked up by the macOS application.

Is there anything I missed to select this device?

**Comment by bitbank2** [comment]
I can add that name as another option for that type of printer. Can you modify the code and confirm that it works after just changing the name? Each printer seems to have unique BLE UUIDs in addition to unique names, so hopefully just the name is different from the MTP-2.

**Comment by uvwxy** [comment]
I wish I could compile this. Unfortunately this is not possible without enrolling into the 🍎 developer program, which I can't ...

**Comment by bitbank2** [comment]
fixed
