### ISSUE TITLE
Support for "SB200" printer 

### ISSUE THREAD

**Issue by Madad1996** [bitbank2/Print2BLE#10]
Could you add support for the "Jooheli" Brand printer?
It identifies as "SB200" over Bluetooth and under Systeminformation it shows the following Informations:
  
SB200:
  Adresse:	00:1D:DF:70:4C:CB
  Hersteller-ID:	0x0057
  Produkt-ID:	0x0005
  Firmwareversion:	0.0.7
  Minor Type:	GenericAudioVideo
  RSSI:	-80
  Dienste:	0x800018 < AVRCP A2DP ACL >

thanks in advance :)

**Comment by Madad1996** [comment]
additional picture of the PCB

![Uploading EA649882-D856-4EB8-A06F-BF0AE7A3183F.jpeg…]()

**Comment by Madad1996** [comment]
additional picture of the PCB

![0BFE34E1-73F5-4B6D-9306-110EEAB99768](https://user-images.githubusercontent.com/18754649/175827563-9bc6fe7f-c920-4f5f-ad03-9841efc7c7f3.jpeg)

**Comment by bitbank2** [comment]
I would appreciate it if you could make the change, confirm it works and do a pull request.

Thanks
