### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by tomhannen** [bitbank2/Print2BLE#11]
Steps to replicate:

Power up the printer. 
The printer is flashing a blue LED.
When I run the app (from the binary in the zip file), and click on Connect, nothing happens:

![ScreenFlow](https://user-images.githubusercontent.com/185299/176886099-27ef6d37-aa54-42ec-bc3a-9d0b3af79866.gif)

I am using:
Cat thermal printer "MINI Printer", which registers as bluetooth name "MX06" using the official Fun Print iOS app
MacBook Pro M1 running MacOS 12.4

Any advice for fault finding appreciated

**Comment by bitbank2** [comment]
That printer name is not in the supported list. There are a bunch of cat/rabbit/panda printer variations and they not only have different BLE names, but different protocols (undocumented) too. I'm sorry, but try changing the code to search for that name and see if the protocol matches the other printers.

**Comment by tomhannen** [comment]
Thanks - I'll try building in XCode and it a go. Whereabouts in the files is the variable for changing the code please?

**Comment by bitbank2** [comment]
https://github.com/bitbank2/Print2BLE/blob/529c68842d484a5f7ca00f8be448deb4e81df2c9/Print2BLE/MyBLE.m#L54

**Comment by tomhannen** [comment]
The code failed when I added "MX06" to the *szTypes array.
But then I also added "PRINTER_CAT" to the ucTypes array and it worked, kind of!

It prints approximately the top quarter of each image I feed it:

![IMG_2075](https://user-images.githubusercontent.com/185299/176934686-13914219-4e9c-4ba3-b6bb-32f797bc858f.jpg)

Feeding works correctly.

Hope this helps with any debugging

**Comment by bitbank2** [comment]
I can't debug this without having the printer here; sorry, I wish I could help more.
