### ISSUE TITLE
Is it possible to use the protocol in iOS project?

### ISSUE THREAD

**Issue by caichunjian520** [bitbank2/Print2BLE#13]
From other repositories for Peripage bluetooth projects, they said the Peripage printer use RFCOMM SPP protocol to send and receive data. But this project uses BLE which is totally different.

1. If Peripage uses BLE for communication between Peripheral and Central, I think it can be used in iOS project?
2. Will it be possible to support Paperang Printer?

**Comment by bitbank2** [comment]
Yes, my MacOS code should be easy to get working on iOS. If a device supports BLE, then you can talk to it with user-written iOS code. What's a "Paperang printer"?

**Comment by caichunjian520** [comment]
Thanks for your reply, if Peripage Printer can communicate using BLE (not RFCOMM SPP), I can start with iOS project.

Paperang printer is also a 58mm thermal printer. The official App Store iOS app include UISupportedExternalAccessoryProtocols in its info.plist, which indicate it is a MFI bluetooth printer. And I can also connect the printer with BLE, so it is also support BLE.
