### ISSUE TITLE
No Content in Window

### ISSUE THREAD

**Issue by Chris-The-Tuner** [bitbank2/Print2BLE#15]
Hi there,

i just tried your Application on my Macbook Pro (M2) but sadly the Window is empty.

I can't even get the MTP-2 Printer to show up in System config to be honest.

**Comment by bitbank2** [comment]
hmm - I had to make a minor change to get it to work on Ventura on my M1 MacBook Air. It behaved the same way initially, then worked fine after my fix. I just tested it on the latest Ventura 13.2 and it works fine. Sorry if I can't recreate the problem, I won't be able to fix it.

**Comment by Chris-The-Tuner** [comment]
Well closing the Issue is not great since it's not clear what happens.
Would it be helpful to run the Program from Terminal to debug if the program does so ?
I'm afraid it may be since my MacBook runs M2, i had a few programs being a bit "problematic" on that platform before.

**Comment by bitbank2** [comment]
I forgot to update the pre-built binary; is that what you're running? If so, I just updated it and it fixes the problem.

**Comment by Chris-The-Tuner** [comment]
Yep i was using the pre-built Binary and low and behold your update fixed the issue.
Runs perfectly now, thank you very mutch for your help and the program.
Just what i needed :)

**Comment by tablatronix** [comment]
Still working? I cannot seem to get any response from the binary, UI shows up buttons do nothing.

**Comment by bitbank2** [comment]
@tablatronix What OS/Processor are you using?

**Comment by tablatronix** [comment]
M1

![Screenshot 2023-10-12 at 6 58 55 AM](https://github.com/bitbank2/Print2BLE/assets/807787/49dd2d40-20d1-4ecf-922f-d37ce60f14e3)

I have others I can try, older arch

**Comment by tablatronix** [comment]
Same result

<img width="590" alt="Screen Shot 2023-10-12 at 5 52 54 PM" src="https://github.com/bitbank2/Print2BLE/assets/807787/c1942cba-f2c4-4b0f-b1a2-99f9237a67a9">
