### ISSUE TITLE
Build under 13.3.1 Intel only prints a few lines on Peripage

### ISSUE THREAD

**Issue by ctshh** [bitbank2/Print2BLE#17]
Built using Xcode 14.3 on an Intel MacBook Pro with macOS 13.3.1 the App finds my printer, but only prints a few lines, then stops. Any ideas what could happen here? Printer works under iOS with the supplied App.
And of course: Thanks! ;)

![Leer 3](https://user-images.githubusercontent.com/6263/231490126-02a6a30e-4d18-4215-afdc-927195ae94c5.png)
[2023-04-12 16:20:09.176415+0200 Print2BL.txt](https://github.com/bitbank2/Print2BLE/files/11212498/2023-04-12.16.20.09.176415%2B0200.Print2BL.txt)
![IMG_3760](https://user-images.githubusercontent.com/6263/231490139-530e0b0b-bfbd-4052-8cba-15793bb7e3f4.jpg)

**Comment by bitbank2** [comment]
The code tries to balance writeWithResponse and write for speed. Try changing the logic to use writeWithResponse all the time. It will go slower, but be more reliable.
