### ISSUE TITLE
Support for Phomemo M02S

### ISSUE THREAD

**Issue by zirafa** [bitbank2/Print2BLE#21]
I was able to get support for Phomemo M02S / Omezizy M02S by adding "M02S" on line 54 and adding "PRINTER_PERIPAGEPLUS" on line 55.

https://github.com/zirafa/Print2BLE/blob/master/Print2BLE/MyBLE.m#L54
https://github.com/zirafa/Print2BLE/blob/master/Print2BLE/MyBLE.m#L55

Through trial and error it seems like the max image size that can be dropped into the Print2BLE app is something like 512 x 270 pixels @ 300 DPI. With 53mm paper in the M02S that ends up being 53mm x 28mm. The app seems to do some automatic resizing based on width. It would be nice if a user could set the desired width and have the height scale proportionally rather than crop.

Here's a template if needed:
https://github.com/zirafa/Print2BLE/blob/master/M02s-template-512x270%40300DPI.jpg

**Comment by zirafa** [comment]
Scratch that last part about max image size. It's just the preview that seems to get cropped weirdly. You can drop in a tall image and although the preview won't show it, when you press print it will work. 🎉

**Comment by bitbank2** [comment]
I just use an NSImageView and let it auto-size on the window. You're welcome to improve the preview code.
