### ISSUE TITLE
Consider moving zip file to Releases?

### ISSUE THREAD

**Issue by jauderho** [bitbank2/Print2BLE#5]
Thanks for adding the feed button, going to try it out now.

Rather than commit the binary/zip to the repo, it might be a good idea to have it on the Releases page instead.

**Comment by bitbank2** [comment]
I defer to more experienced "githubbers" to make it so :)

**Comment by jauderho** [comment]
If you navigate to https://github.com/bitbank2/Print2BLE/releases/new, there should be a page that allows you to create a new release every time you build. 

Under the `Choose a tag` dropdown, you can add a new tag. I advise adhering to semantic versioning so to start, maybe `v0.1.0`

You should be able to drag and drop the zip file into the specified area. Once you are ready, simply hit `Publish` and you have a new release.

Let me know if you have more questions.
