### ISSUE TITLE
Image prints are truncated

### ISSUE THREAD

**Issue by andypiper** [bitbank2/Print2BLE#8]
On a GB03 printer (PR #7) everything appears to be OK, but the prints are too "short" - only about ~20% of the image (vertically) is printed. Unclear whether this is something to do with the height calculation - the preview image shows up correctly in the window after being dropped in.

**Comment by andypiper** [comment]
My Objective-C / Mac app debugging skills are limited but I think somewhere in the `printImage()` function it's not fully copying the data between the dither and the output to send to the printer. It looks like it is doing this inconsistently as well, i.e the same file can be printed with different numbers of scanlines, always only a small amount of the complete height of the image.

**Comment by bitbank2** [comment]
That code sends every scanline, but I use a personal 'guess' to speed up BLE transmission. The MyBLE::scanLine() method tries to send 15 out of 16 packets withoutResponse and 1 withResponse to speed things up. Sending everything withResponse will increase the reliability, but slow it down quite a bit. Please give it a try on your printer and see if sending all packets withResponse fixes it.
